### ISSUE TITLE
Nonce Displaying as 򅻟

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#113]
https://testnet-explorer.gochain.io/tx/0xbb2895fd2a997d4d71c0065bc1428262f2d16d4aa2606e21356decac138a75e3

![screenshot from 2018-09-25 09-36-42](https://user-images.githubusercontent.com/1194128/46021551-90213680-c0a6-11e8-8ba0-7f2745718968.png)

This appears to affect every tx

**Comment by jmank88** [comment]
This is still happening, though only for some txs:
![Screenshot from 2019-05-01 09-41-09](https://user-images.githubusercontent.com/1194128/57022645-62c8d800-6bf5-11e9-9dd0-487779f03d41.png)
https://explorer.gochain.io/tx/0x3dc812dab5985e1b1cbc775b7f27dc13a882446b50ff47b28297dcbc0727f29a

**Comment by jmank88** [comment]
Some are missing as well:
![Screenshot from 2019-05-01 10-39-48](https://user-images.githubusercontent.com/1194128/57025687-7f690e00-6bfd-11e9-9bb6-7c49742ae3d5.png)
https://explorer.gochain.io/tx/0xab821dc730491e58cd38605e8c795ef3aefafc02e9c5b7c44d18e1a823f6c2bd

**Comment by r-gochain** [comment]
removed some transactions with bad nonce, should be refilled soon

**Comment by r-gochain** [comment]
Checked most of the failed Txs - looks good (mainnet)
@jmank88 could you confirm?

**Comment by jmank88** [comment]
Looks good.
