### ISSUE TITLE
Gas Price Missing units

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#114]
![screenshot from 2018-09-25 09-41-59](https://user-images.githubusercontent.com/1194128/46021990-674d7100-c0a7-11e8-93ac-55af6ebcb24b.png)

In the old version, it was displayed in gwei. (decimals make it weird though)

![screenshot from 2018-09-25 09-43-52](https://user-images.githubusercontent.com/1194128/46022071-877d3000-c0a7-11e8-80ac-d57fa9636800.png)

**Comment by r-kononov** [comment]
![image](https://user-images.githubusercontent.com/40002763/46419758-632ced80-c750-11e8-9365-19401a2e1e73.png)
