### ISSUE TITLE
Tx details should display gas used

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#115]
The gas fee is calculated from the gas used (from the receipt), but gas used is not displayed anywhere.

![screenshot from 2018-09-25 09-45-08](https://user-images.githubusercontent.com/1194128/46022180-bb585580-c0a7-11e8-87c2-09650303afd9.png)

Can we add 'gas used' and also reorder the fields to `Price`, `Limit`, `Used`, `Fee`?

**Comment by bergauz** [comment]
<img width="545" alt="screenshot 2018-10-15 at 21 50 02" src="https://user-images.githubusercontent.com/42649300/46962187-57341a80-d0c4-11e8-9836-aa2f3401740d.png">

**Comment by treeder** [comment]
@jmank88 I think "fee" might actually be "used", if so we should change the name to "used" @bergauz . 

@bergauz in that screenshot you just posted, what's the difference between "limit" and "used"?

**Comment by jmank88** [comment]
This looks correct to me. This tx just happens to have set the gas limit exactly to what was needed.

**Comment by bergauz** [comment]
@treeder so gas_used is calculated based on = gas_fee / gas_price

**Comment by jmank88** [comment]
![screenshot from 2018-10-21 12-14-55](https://user-images.githubusercontent.com/1194128/47269996-ef019080-d52a-11e8-84de-ea107adc93eb.png)
