### ISSUE TITLE
Make Parent Block Hash a Link

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#116]
![screenshot from 2018-09-25 09-49-52](https://user-images.githubusercontent.com/1194128/46022535-6ec14a00-c0a8-11e8-8c2e-614c353014b5.png)
In old explorer, parent block hash is a hyperlink to that block:
![screenshot from 2018-09-25 09-49-56](https://user-images.githubusercontent.com/1194128/46022540-6ff27700-c0a8-11e8-9ed4-2336cc169ae3.png)

**Comment by r-kononov** [comment]
![image](https://user-images.githubusercontent.com/40002763/46419797-78a21780-c750-11e8-9244-043a419ad336.png)
