### ISSUE TITLE
Validating contracts

### ISSUE THREAD

**Issue by treeder** [gochain-io/explorer#128]
This sort of exists in the old explorer: https://explorer.gochain.io/addr/0x3b23f2485253c98303b8f9154e769345d83051fc#tab_addr_3

But apparently doesn't work. Can we add something like this to the new explorer?

**Comment by r-kononov** [comment]
@treeder any example what should be there? bytecode?

**Comment by treeder** [comment]
Etherscan has this: https://etherscan.io/verifyContract?a=0xdeceac4cbb3e30a40091e7d73d0a16ddf88f1c6d
