### ISSUE TITLE
Some minor fixes on tx details page (and applies to other pages too)

### ISSUE THREAD

**Issue by treeder** [gochain-io/explorer#132]
* [x] Make text bigger on details pages
* [x] Put "From" before "To"
* [x] Drop trailing zeros

![screen shot 2018-10-10 at 3 57 47 pm](https://user-images.githubusercontent.com/75826/46770738-7f2b1480-cca5-11e8-8651-3dade1366224.png)

**Comment by r-kononov** [comment]
lgtm
