### ISSUE TITLE
Add a bunch of stuff to GO-20 page

### ISSUE THREAD

**Issue by treeder** [gochain-io/explorer#149]
Total supply
Decimals
Name
etc

**Comment by bergauz** [comment]
<img width="418" alt="screenshot 2018-11-01 at 20 26 50" src="https://user-images.githubusercontent.com/42649300/47859194-f755a780-de17-11e8-80f9-a7bdb89dadcf.png">
<img width="1280" alt="screenshot 2018-11-01 at 20 26 25" src="https://user-images.githubusercontent.com/42649300/47859235-105e5880-de18-11e8-8b50-14fd193ad31d.png">
