### ISSUE TITLE
Duplicate entries found in Rich list of Explorer

### ISSUE THREAD

**Issue by cryptolanka1** [gochain-io/explorer#150]
0x946dc06684EE56eb76fd32bD014D3381943D77Ae
:0x946dc06684ee56eb76fd32bd014d3381943d77ae

0xFb4546527f420264d8E0A9931A31666211F89d48
:0xfb4546527f420264d8e0a9931a31666211f89d48

0xdd9ce1d9d548d0c5ac333a1b2d2042281886c5ea
:0xDD9Ce1D9d548d0C5ac333A1B2d2042281886c5ea

0x3ad14430951aBa12068A8167CeBE3ddd57614432
:0x3ad14430951aba12068a8167cebe3ddd57614432

0xEd7F2e81B0264177e0df8f275f97Fd74Fa51A896
:0xed7f2e81b0264177e0df8f275f97fd74fa51a896

0xE1200Caf0d92018FE111943FaF91a0c5f6DB34d1
:0xe1200caf0d92018fe111943faf91a0c5f6db34d1

0x1ee4BAf2Cccc633B8E2c06a3ac20319610Cf3cd5
:0x1ee4baf2cccc633b8e2c06a3ac20319610cf3cd5

0x31f0856de90f1fea05e538e3c929422e063adfe0
:0x31f0856dE90f1Fea05E538e3C929422E063aDFE0

0x56d80Ae12A16cFc5084Cdebd6cBeC30619Fd3B5b
:0x56d80ae12a16cfc5084cdebd6cbec30619fd3b5b

0xd1d4B925ed519E053eCFB6E3ddC49Bb1Cf52AB39
:0xd1d4b925ed519e053ecfb6e3ddc49bb1cf52ab39

0x74e8082d4e6EA78FA964e4279E31061c6aF7DC5E
:0x74e8082d4e6ea78fa964e4279e31061c6af7dc5e

0x1d20466dc0b06b056294812a379544655bf754a0
:0x1d20466dc0b06B056294812a379544655BF754A0

0x5A9dfc23aa727f76Fb0fAcD5b4Fae8Fec3059700
:0x5a9dfc23aa727f76fb0facd5b4fae8fec3059700

0x12b353D1a2842D2272aB5A18C6814D69f4296873
:0x12b353d1a2842d2272ab5a18c6814d69f4296873

0xb032fefc4c734e31156fdc410980357785f9ccdf
:0xB032FeFC4C734E31156FDC410980357785F9cCDF

0x1324567409b771d09a6abdb4af249b7fe2de45fc
:0x1324567409b771D09A6aBdb4Af249B7fe2De45fc

0x061eF2888EfeC8beD81b38038348fFDE850B987a
:0x061ef2888efec8bed81b38038348ffde850b987a

0x48c67d87cd7d716ec044dbe33a0152557bf86062
:0x48c67D87cd7D716ec044DBE33a0152557Bf86062

0x4F3321F12060bF2734f3d9Bd82AF18c92D15D3d9
:0x4f3321f12060bf2734f3d9bd82af18c92d15d3d9

0x9be544b97582446bb79395225f731e18feab8d59
:0x9bE544b97582446BB79395225f731E18FEAB8D59

0x76c8b15940c5b0775389d4e6adb854182930a0ee
:0x76C8B15940C5b0775389d4e6aDB854182930A0ee

0xbf3f325510b153516fd75aec6cb8360958960cc6
:0xBf3F325510b153516FD75AEC6Cb8360958960Cc6

0x372ecDF8d806cB437a47332c46e14EE54b5bB497
:0x372ecdf8d806cb437a47332c46e14ee54b5bb497

0xD0ed7d991D8b60ADCDFFF545D10E0c7060B1B61B
:0xd0ed7d991d8b60adcdfff545d10e0c7060b1b61b

0x22D68B3bf15B37605c29E2477Ef55729593cF40a
:0x22d68b3bf15b37605c29e2477ef55729593cf40a

0xd707552e5cc8e894d76fd0c82eb368c2f3a4af1a
:0xD707552E5cc8E894d76FD0C82eB368c2F3A4Af1a

0x3b23f2485253c98303b8f9154e769345d83051fc
:0x3b23f2485253c98303B8F9154E769345d83051FC

0x6F77bCd21b90E36A8E69939384A8Dd2185A0E817
:0x6f77bcd21b90e36a8e69939384a8dd2185a0e817

0x37fe4dbcf414b8b662ad0d673501d16913272d83
:0x37fE4DbcF414b8B662aD0d673501d16913272D83

0x9dB67314205d56851056FD6Fa0781a5Feb6D5791
:0x9db67314205d56851056fd6fa0781a5feb6d5791

0x2f89e70c40f0f0fb07bc64daf306f01c074a8253
:0x2f89e70c40F0F0Fb07bc64DaF306f01C074a8253

0x0A2CF69A10459f57F25aaDb051188a39Ccb92A30
:0x0a2cf69a10459f57f25aadb051188a39ccb92a30

0xAeDD0b2f0DA074Ce05d63a3c6836243191876925
:0xaedd0b2f0da074ce05d63a3c6836243191876925

0x58C3fea7f735931e0d503F2717ADC64217e355A1
:0x58c3fea7f735931e0d503f2717adc64217e355a1

0x04278934b278620edaff2679273009b03401766f
:0x04278934b278620EdAfF2679273009B03401766f

0xf84caf82a58819c08A0548E378D54e73AD9c823B
:0xf84caf82a58819c08a0548e378d54e73ad9c823b

These are the entries I found today .. 10/28/2018
some times it takes more than 8 hours to show the correct amount on rich list..some tokens reflect right away but some don't

**Comment by jmank88** [comment]
What's more, the duplicates show *very* different balances:
![screenshot from 2018-10-28 08-00-27](https://user-images.githubusercontent.com/1194128/47616197-94ff4e80-da87-11e8-8de9-65cf0309873b.png)
![screenshot from 2018-10-28 08-00-35](https://user-images.githubusercontent.com/1194128/47616195-916bc780-da87-11e8-8311-9b325b9b12b9.png)

**Comment by r-kononov** [comment]
Fix deployed, list of addresses above has been cleaned, need some time to refill.
Root of the issue was in data inconsistency introduced earlier.
