### ISSUE TITLE
Replace relative block times

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#151]
Relative time for blocks isn't particularly useful:
![screenshot from 2018-10-28 08-06-21](https://user-images.githubusercontent.com/1194128/47616268-68980200-da88-11e8-9bcd-523476227027.png)
What about just showing the static timestamp instead? Or both, with the relative time in parentheses like on the block details page (or maybe just a tooltip on hover to save some space)?
![screenshot from 2018-10-28 08-08-51](https://user-images.githubusercontent.com/1194128/47616293-c1679a80-da88-11e8-9162-cc359c636f26.png)

**Comment by bergauz** [comment]
Showing them on hover or tooltip is not the best choice, cause it's data table, user should see all the data without any action. Let's show both static and relative time.

**Comment by jmank88** [comment]
I agree in general, but in this case the relative time is derived directly from the actual timestamp anyways, and is also way less precise, so I don't think it's a big deal to make it secondary info (or just remove it entirely) in order to save space - maybe just for the mobile view.

**Comment by bergauz** [comment]
<img width="1280" alt="screenshot 2018-10-29 at 22 14 13" src="https://user-images.githubusercontent.com/42649300/47663948-3b526d80-dbc8-11e8-9cb1-88a476092a62.png">
![photo_2018-10-29_22-15-21](https://user-images.githubusercontent.com/42649300/47664174-b3209800-dbc8-11e8-8449-5e9796ec28f0.jpg)
@jmank88 what do you think about mobile view?
