### ISSUE TITLE
https://explorer.gochain.io/richlist is not showing up properly on Iphone browsers

### ISSUE THREAD

**Issue by cryptolanka1** [gochain-io/explorer#152]
It seems the explorer was not designed as Responsive web.. you make make all the pages as responsive web to appear properly

**Comment by bergauz** [comment]
![photo_2018-10-29_14-53-30](https://user-images.githubusercontent.com/42649300/47639054-91a0bb80-db8a-11e8-9d94-4a75b75feccd.jpg)
![photo_2018-10-29_14-53-29](https://user-images.githubusercontent.com/42649300/47639055-91a0bb80-db8a-11e8-98e8-246803f7b190.jpg)
So the main issue is tables, the best way to make them fit are making them scrollable. I'll change them to cards (div).

**Comment by bergauz** [comment]
@cryptolanka1 can you attach screens if possible pls

**Comment by bergauz** [comment]
![1](https://user-images.githubusercontent.com/42649300/47716688-b1f57680-dc6d-11e8-86dc-bed31a4d0764.jpg)
![2](https://user-images.githubusercontent.com/42649300/47716708-bde13880-dc6d-11e8-8369-387e5cfe545f.jpg)
![4](https://user-images.githubusercontent.com/42649300/47716709-bde13880-dc6d-11e8-8414-8b3d24465ddc.jpg)
![3](https://user-images.githubusercontent.com/42649300/47716710-bde13880-dc6d-11e8-8a94-ffaa66378836.jpg)

**Comment by bergauz** [comment]
![mobiles](https://user-images.githubusercontent.com/42649300/47717280-8d020300-dc6f-11e8-90e8-d263583739dd.png)

**Comment by jmank88** [comment]
@cryptolarity It's case sensitive - https://explorer.gochain.io/circulatingSupply

**Comment by bergauz** [comment]
<img width="325" alt="screenshot 2018-11-01 at 20 50 34" src="https://user-images.githubusercontent.com/42649300/47859322-46034180-de18-11e8-83d6-b63dae6eb5e4.png">
