### ISSUE TITLE
Display txs in last week/24hrs

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#157]
Explorer currently shows total transactions. We should consider displaying transactions in the last week and last 24 hours as well.
![screenshot from 2018-11-06 09-33-40](https://user-images.githubusercontent.com/1194128/48074670-14d39a00-e1a7-11e8-84b8-c3654e8bc4e4.png)

**Comment by bergauz** [comment]
@jmank88 last week = now - 7 days?

**Comment by jmank88** [comment]
Yes, I think a relative range computed when the page first loads makes sense. No need to update as blocks come in, only if they refresh. Maybe a tooltip with the exact ranges (to the second) being used.

**Comment by bergauz** [comment]
<img width="1264" alt="screenshot 2018-11-08 at 00 53 47" src="https://user-images.githubusercontent.com/42649300/48153571-c92d0780-e2f0-11e8-88fb-67224c2bba2b.png">

**Comment by r-kononov** [comment]
@jmank88 do you think that 24H and total would be fine?(7 days is a bit heavy one, even with index, and I don't want to introduce caching atm)

**Comment by jmank88** [comment]
7d was actually the initial request, with comparison to https://blocktivity.info/ in mind.

**Comment by jmank88** [comment]
Oh wait that is actually average per 24hr, over the last 7 days. So maybe just 24hr is fine for now.

**Comment by jmank88** [comment]
Thinking about this more, why would the size of range affect the query time at all? I'm not very familiar with mongo or the data model being used, but if this is indexed properly, shouldn't it just be a binary search for a timestamp? The particular timestamp and the number of txs in the range shouldn't matter.

**Comment by jmank88** [comment]
But 'counting' should literally just be 'end position' minus 'start position', and binary search for those positions in the index should be the same no matter the range. Seems like mongo should be able to do better.

**Comment by jmank88** [comment]
These docs make it sound like it should be doing what I expected: https://docs.mongodb.com/manual/reference/method/db.collection.count/#index-use

**Comment by r-kononov** [comment]
> But 'counting' should literally just be 'end position' minus 'start position', and binary search for those positions in the index should be the same no matter the range. Seems like mongo should be able to do better.

I'm expecting the same maybe it's fine with this volume of records/amount of indexes but  I'll play a bit with this query/index options

**Comment by bergauz** [comment]
<img width="690" alt="screenshot 2018-11-13 at 18 00 22" src="https://user-images.githubusercontent.com/42649300/48412182-19cbb700-e76e-11e8-9098-47ba01800e13.png">
