### ISSUE TITLE
add info for search engines

### ISSUE THREAD

**Issue by bergauz** [gochain-io/explorer#159]
<img width="1119" alt="screenshot 2018-11-08 at 17 02 13" src="https://user-images.githubusercontent.com/42649300/48194820-3cc62780-e378-11e8-9e06-8ba72d880b84.png">
Like gochain.io
<img width="1164" alt="screenshot 2018-11-08 at 17 02 20" src="https://user-images.githubusercontent.com/42649300/48194849-58c9c900-e378-11e8-84c7-442a86b1e1f3.png">

**Comment by treeder** [comment]
"GoChain Explorer allows you to explore and search the GoChain blockchain for transactions, addresses, tokens, prices and other activities taking place on GoChain."
