### ISSUE TITLE
Is it possible to show tx logs when viewing a transaction?

### ISSUE THREAD

**Issue by treeder** [gochain-io/explorer#165]
So you could see what happened, whether it's an error or successful events, eg:

https://explorer.gochain.io/tx/0xbe3844129257a2bea4fa17aab608a6f18ad718a0ef38cc4124dd594c3a30cbf0

I think it errored but not sure.

**Comment by r-kononov** [comment]
logs are empty, but even if they are not, not sure that we could decode them without knowing ABI

![image](https://user-images.githubusercontent.com/40002763/49275645-1b071e80-f4a6-11e8-98b3-967ec55c8761.png)
https://codeburst.io/deep-dive-into-ethereum-logs-a8d2047c7371
