### ISSUE TITLE
add time chart with gochain info (price, tx count) - home page

### ISSUE THREAD

**Issue by bergauz** [gochain-io/explorer#166]
@r-kononov @treeder @jmank88 
Smth like this
<img width="1054" alt="screenshot 2018-11-25 at 14 33 57" src="https://user-images.githubusercontent.com/42649300/48977153-35fd1b80-f0bf-11e8-8d5b-8b070fc8c140.png">

**Comment by r-kononov** [comment]
btw there is stats collection - check it's content
