### ISSUE TITLE
GO-20 not showing up as a GO-20.

### ISSUE THREAD

**Issue by treeder** [gochain-io/explorer#169]
This is apparently a GO-20, but it doesn't show as one: https://testnet-explorer.gochain.io/addr/0xCDe8178509cab657dc9B7c4C3B37C455FA99A348?addr_tab=transactions

**Comment by r-kononov** [comment]
@treeder I don't see any code at this address

![image](https://user-images.githubusercontent.com/40002763/49012483-be54ec80-f1a3-11e8-84a8-881b85ea2965.png)
