### ISSUE TITLE
Comma-format token total supply

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#171]
We should use the more readable comma-format for this field.
`1000000000000000000000000000`->`1,000,000,000,000,000,000,000,000,000`
![screenshot from 2018-11-29 10-26-31](https://user-images.githubusercontent.com/1194128/49236225-46640d80-f3c1-11e8-8fd3-13085c20f7cc.png)
From https://explorer.gochain.io/addr/0x37C93A80b5702A820CbC3050f0e9eC48a1D5e738?addr_tab=internal_transactions

**Comment by r-kononov** [comment]
on testnet

**Comment by jmank88** [comment]
![screenshot from 2018-12-04 07-14-52](https://user-images.githubusercontent.com/1194128/49444291-4f275b80-f794-11e8-9205-bfa3d9cc5682.png)
