### ISSUE TITLE
Apply GO20 decimal conversion

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#174]
GO20 tokens should display with the decimals conversion applied:
![screenshot from 2018-11-29 10-24-44](https://user-images.githubusercontent.com/1194128/49237899-e53e3900-f3c4-11e8-8717-96cfc099e7b0.png)
![screenshot from 2018-11-29 10-24-47](https://user-images.githubusercontent.com/1194128/49238041-377f5a00-f3c5-11e8-9100-023246243f36.png)
![screenshot from 2018-11-29 11-05-30](https://user-images.githubusercontent.com/1194128/49238760-bde86b80-f3c6-11e8-93e2-a23745f3b25a.png)
Should be:
```
Total supply: 1,000,000,000
0.1
1
999,937,901.266704936000000003
25,017
...
```
(from https://explorer.gochain.io/addr/0x37C93A80b5702A820CbC3050f0e9eC48a1D5e738?addr_tab=transactions)

**Comment by r-kononov** [comment]
The same with token holder balances and transactions I suppose?

**Comment by jmank88** [comment]
> The same with token holder balances and transactions I suppose?

Yes, the second screenshot was txs, and now I added a third for holders.

**Comment by r-kononov** [comment]
deployed to testnet

**Comment by jmank88** [comment]
Looks good on mainnet:
![screenshot from 2018-12-04 07-13-21](https://user-images.githubusercontent.com/1194128/49444225-1ab39f80-f794-11e8-983e-0cab7a131ee9.png)
![screenshot from 2018-12-04 07-13-24](https://user-images.githubusercontent.com/1194128/49444227-1c7d6300-f794-11e8-83f7-08612af25546.png)
Do we have any non-18 decimal tokens to try some other cases?
