### ISSUE TITLE
Tokens: link internal txs and holders

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#177]
These hex address and hash fields can all be links:
![screenshot from 2018-12-04 07-15-30](https://user-images.githubusercontent.com/1194128/49444330-73833800-f794-11e8-9b76-5805d15b4340.png)
![screenshot from 2018-12-04 07-15-42](https://user-images.githubusercontent.com/1194128/49444332-754cfb80-f794-11e8-8dfd-93aa1b209e72.png)
(https://explorer.gochain.io/addr/0x37C93A80b5702A820CbC3050f0e9eC48a1D5e738?addr_tab=internal_transactions)
![screenshot from 2018-12-04 07-15-36](https://user-images.githubusercontent.com/1194128/49444334-767e2880-f794-11e8-9758-dc58d96f11ed.png)
(https://explorer.gochain.io/addr/0x37C93A80b5702A820CbC3050f0e9eC48a1D5e738?addr_tab=holders)

**Comment by r-kononov** [comment]
Are you sure that they could be links to addresses/transactions or you want to keep list/balance for internal token holders/transactions per contract?
