### ISSUE TITLE
amount of GO displayed as sent appears as '0' if > 18 decimals

### ISSUE THREAD

**Issue by cryptolarity** [gochain-io/explorer#178]
Transactions that transfer less than 18 decimals worth of GO do not display and show as '0' GO sent, this transaction was 1e-87 GO - https://explorer.gochain.io/tx/0x3bbda6dd835f46bf79a433a0085c880d633e808c95d9e39345e04355f2338723

**Comment by cryptolarity** [comment]
Per @jmank88 seems to be a Turbowallet bug - https://t.me/go_chain/279960

**Comment by jmank88** [comment]
https://github.com/turbowallet/support/issues/1

**Comment by r-kononov** [comment]
![image](https://user-images.githubusercontent.com/40002763/49745518-56d18d80-fcc9-11e8-88ff-038484be3843.png)

**Comment by r-kononov** [comment]
value: 0x0
