### ISSUE TITLE
Add filters into /api/

### ISSUE THREAD

**Issue by alexandrebelrouchi** [gochain-io/explorer#184]
Hi guys,

Would be really nice to add filters such as Input data: 

like /api/address/transactions?input_data=XXXXXXX
like /api/address/transactions?created_at=XXXXXXX

Very useful for plenty of people I guess and would lighten up big time bandwidth cost as currently we need to load the whole DB to do it

Also, start fetching list from DESC/ASC

**Comment by bergauz** [comment]
What about smth like this: 
POST:
{
  limit?: number,
  offset?: number,
  sort?: ASC | DESC,
  where?: {
    created_at: ''",
    other_fields...
  }
}
or GET: 
{
  limit?: number,
  offset?: number,
  sort?: ASC | DESC,
  created_at: '',
  other_fields...
}

**Comment by r-kononov** [comment]
where?: {
created_at: ''",
other_fields...
}

bad Idea, we don't have indexes for every field and it doesn't make sense

**Comment by jmank88** [comment]
@alexandrebelrouchi Can you be more specific about the queries you had in mind? 
Would `input_data` be a full match? Or a substring match? Or a regex?
Would `created_at` be exact? Or would before/after variants be necessary as well?

**Comment by alexandrebelrouchi** [comment]
Input_data would be a regex if possible
Created at would be nice with a between X & X

**Comment by alexandrebelrouchi** [comment]
> where?: {
> created_at: ''",
> other_fields...
> }
> 
> bad Idea, we don't have indexes for every field and it doesn't make sense

Yes but wouldn't that be better instead of fetching my 5000 transactions all the time?

**Comment by r-kononov** [comment]
> > where?: {
> > created_at: ''",
> > other_fields...
> > }
> > bad Idea, we don't have indexes for every field and it doesn't make sense
> 
> Yes but wouldn't that be better instead of fetching my 5000 transactions all the time?
> Fetching 5k transactions every x seconds * 500 users for example would cost so much bandwidth ;)
> 
> I don't see how it doesn't make sense... way lighter on the backend

hmm we have 795,608,660 transactions atm and 13 fields - how much memory would that costs to have an index for every field and also it won't help for some of the regex queries (only for prefix ones), so I think even 1 user with a regex query could force full scan of the transaction collection which could lead to slowdown.

I'll add indexes and API for created_at_gt and created_at_lt and will test regexp/substring performance

**Comment by r-kononov** [comment]
@alexandrebelrouchi https://testnet-explorer.gochain.io/api/address/0x00AF4e701116bA2b08e1e2646D41eAce7b234203/transactions?from_time=2018-12-24T10:39:13Z&to_time=2018-12-25T10:39:13Z

feel free to test.

Could you share your use case for input_data - because I don't think that I could add search with regex by this field - it will require full collection scan which would kill the db.

**Comment by alexandrebelrouchi** [comment]
That's amazing! Thank you
Is it possible to filter just Input_data Empty or not? (not a regex)

**Comment by r-kononov** [comment]
@alexandrebelrouchi yep thats possible, give me a day to update testnet/mainnet explorer to update indices

**Comment by r-kononov** [comment]
@alexandrebelrouchi added parameter - input_data_empty (could be true or false)
```curl "https://testnet-explorer.gochain.io/api/address/0x00AF4e701116bA2b08e1e2646D41eAce7b234203/transactions?input_data_empty=true"```
