### ISSUE TITLE
Nav too wide

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#188]
At minimum width (`850px`) the nav bar looks like this:
![screenshot from 2018-12-11 05-09-25](https://user-images.githubusercontent.com/1194128/49796709-0d059900-fd03-11e8-924b-cd253182e857.png)
Actual current minimum is `~1155px` (at which point nav is already wrapping):
![screenshot from 2018-12-11 05-11-15](https://user-images.githubusercontent.com/1194128/49796784-40e0be80-fd03-11e8-9b7a-1f75b5b2846d.png)

Some ideas to reduce required width:

- `Network Stats`->`Netstats`
- Reduce search bar width
- Break apart local nav from external links (stats, wallet) and only leave one in the top bar

**Comment by inkberk** [comment]
moving to the left side to drawer should fix it

**Comment by bergauz** [comment]
Moving to the left side should fix it

**Comment by treeder** [comment]
Verity contract could probably be moved to the contract details page. ie: after searching for it.

**Comment by bergauz** [comment]
@treeder  it's already there, it've been put to menu to notify users that there's verification option, temporary deleted from menu. When menu gonna be moved to left side drawer we can bring it back
