### ISSUE TITLE
GO-20 holders and internal TX not showing up.

### ISSUE THREAD

**Issue by brockmcblockchain** [gochain-io/explorer#191]
I recently deployed a Go-20 on testnet.  Some of the data has synced up but it's still not showing any internal transactions or holders.  

After creating the contract here: https://testnet-explorer.gochain.io/addr/0x4228Af68CC0a0B4585f46a165f656Bcafbec01Ad?addr_tab=internal_transactions

I used the Go Wallet to interact with my smart contract and send a wallet 50 tokens.   If I do a balance of (wallet: 0xEB682A6F1F05e47aBD9415441d70254307269F00) the tokens show up fine.  However the tokens don't show up on the explorer and the holder and txs aren't showing up on the contract either.  

Please let me know if I can provide more information.

![screen shot 2018-12-13 at 6 01 56 pm](https://user-images.githubusercontent.com/39677511/49972929-31c75f80-ff01-11e8-9ac0-2d4a4a58b84e.jpg)

**Comment by r-kononov** [comment]
We are aware of this problem, I'm working on solution

**Comment by r-kononov** [comment]
fixed
