### ISSUE TITLE
FEATURE REQUEST(S): Pagination for additional blocks on homepage

### ISSUE THREAD

**Issue by brockmcblockchain** [gochain-io/explorer#192]
If you're on the rich list you can click "more" at the bottom to load more.  There isn't a way goto the 'previous' set of blocks in cronological order.  You could lazy load them but this could get messy -- adding a /page/2  ... page/n   would be prefered most likely.   The content would keep shifting as blocks  keep getting added which I think is ok.
**Use case:** being able to find blocks more easily that may have been pushed off the front page.

One cool idea that may help overcome this may be to add a "bookmarklet" type icon that a user can click on and pull a view that starts with that block number.  
**Use case:** If they were researching some sort of transactions they could have a way of saving/sharing their path to return to later or have someone else look into as well.

**Comment by r-kononov** [comment]
Don't think this is a good idea to make the main page paginated - because it's being updated every 5 seconds, so scrolling would be not predictable. But you could get all this information from the API - https://github.com/gochain-io/explorer#get-the-list-of-the-most-recent-blocks
