### ISSUE TITLE
Internal Tx Timestamp Incorrect

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#194]
From: https://testnet-explorer.gochain.io/addr/0x4228Af68CC0a0B4585f46a165f656Bcafbec01Ad?addr_tab=internal_transactions
![screenshot from 2018-12-18 12-09-58](https://user-images.githubusercontent.com/1194128/50173727-eb398280-02bd-11e9-9731-4d7f708d6fe3.png)
Here we see two txs with recent timestamps, but if we click through to either one: (https://testnet-explorer.gochain.io/tx/0xe435cae3c85ae8633c554a6310e46750a3454c8d4d3fad74371d251a949ea389)
![screenshot from 2018-12-18 12-11-19](https://user-images.githubusercontent.com/1194128/50173783-0c01d800-02be-11e9-9fdf-9d406573bea7.png)
We see a completely different timestamp. I'm guessing the table is showing an 'imported at' timestamp.

**Comment by r-kononov** [comment]
yep, will fix
