### ISSUE TITLE
Not clearing the tx list when looking up another address

### ISSUE THREAD

**Issue by treeder** [gochain-io/explorer#201]
To reproduce:

* Enter an address on homepage and enter to go to the wallet
* Enter another address on the wallet page and submit, it will show a mix of transactions from both the previous wallet and the new wallet

**Comment by treeder** [comment]
This still isn't fixed.

**Comment by bergauz** [comment]
@treeder it's working fine as I've checked, can you check it

**Comment by treeder** [comment]
Haven't seen it lately, so I'll close it for now.
