### ISSUE TITLE
Get Go-20 token transaction history for an address

### ISSUE THREAD

**Issue by flxwallet-dev** [gochain-io/explorer#207]
Would it be possible to include additional arguments to either the 'transactions' or 'internal_transactions' explorer endpoints to get Go-20 token transaction history for a specific address. For example,

GET /api/address/{address_hash}/transactions
- Include 'contract_address_hash' parameter to get Go-20 token transaction history for 'address_hash'

GET /api/address/{address_hash}/internal_transactions
- Include 'from_address'/'to_address' parameter to filter Go-20 token transaction history to only include transaction for a specific address. This prevent having to search through entire internal transaction history to get list of Go-20 token transactions for a specific address

Thanks

**Comment by r-kononov** [comment]
@flxwallet-dev 
quick question -  'from_address'/'to_address' what if user used both - should we use OR or AND?

**Comment by flxwallet-dev** [comment]
> @flxwallet-dev
> quick question - 'from_address'/'to_address' what if user used both - should we use OR or AND?

I would prefer OR, but I think that would be inconsistent with how the existing parameters work, such as 'limit' or 'skip' which are AND.

So I would suggest AND and maybe use a different parameter name for an OR query.

One other question, I been testing the 'internal_transactions' endpoint by sending Turbo Wallet Tokens from one wallet to another and notice that the 'internal_transactions' only includes the last transaction if wallet A sends multiple transaction to wallet B. For example, I made the following two transactions:

(Tx1) Sent 0.0005 TURBO from 0x8d31... to 0x89d7...
https://explorer.gochain.io/tx/0x3fd0b20e3e17be4ef083584eab49feee73ff21de28020284aa75b4a352b023a3

(Tx2) Sent 0.0001 TURBO from 0x8d31... to 0x89d7...
https://explorer.gochain.io/tx/0x61b57d8a5aa62cbabedad9ceb5d2c857c39dad1fa94d9bfae35c2248a86b5de6

(Turbo Go-20)
https://explorer.gochain.io/addr/0x37C93A80b5702A820CbC3050f0e9eC48a1D5e738?addr_tab=internal_transactions

Tx1 did appear in 'internal_transactions' for TURBO, but after sending Tx2, Tx2 appear in 'internal_transactions' and Tx1 disappear from the history. Is this normal behavior. If so, maybe 'internal_transactions' is not the best way to get Go-20 transaction history for an address.

**Comment by r-kononov** [comment]
Update API and fixed the bug, going to update testnet and mainnet on next week (after the review)

**Comment by jmank88** [comment]
> Is this normal behavior.

No, it looks like a bug. You can see Tx1 in the tx history for the contract, but not in the internal list. Perhaps this should be a separate issue? @rkononov
