### ISSUE TITLE
Excess Decimals

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#21]
Maybe we can truncate trailing decimal 0s:
![screenshot from 2018-05-18 06-58-04](https://user-images.githubusercontent.com/1194128/40233512-e862d898-5a68-11e8-87b0-89ad9d13765b.png)
![screenshot from 2018-05-18 06-58-08](https://user-images.githubusercontent.com/1194128/40233514-ea8a9fc0-5a68-11e8-9244-b39d7ddbd46e.png)

**Comment by rkononov** [comment]
![image](https://user-images.githubusercontent.com/187434/40439583-2c83d04a-5edd-11e8-97ad-b40d00f153ae.png)
