### ISSUE TITLE
Support ERC-20 extensions, like ERC-223

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#212]
GO/ERC-20 token contracts are recognized and displayed differently in the interface:
![screenshot from 2019-01-18 07-39-59](https://user-images.githubusercontent.com/1194128/51390216-472d3c00-1af4-11e9-8ecd-9e413e1e2700.png)
https://explorer.gochain.io/addr/0x37C93A80b5702A820CbC3050f0e9eC48a1D5e738

The [ERC223 token standard](https://github.com/ethereum/EIPs/issues/223) is a superset of ERC20, so it should display as a token in the interface as well, and it should be trivial to do so. There are other similar token standards as well, can we support them all automatically?

[Here is an ERC223](https://explorer.gochain.io/addr/0xA7620862540F635342B166206108D7B31C875Dd8)
![screenshot from 2019-01-18 07-41-44](https://user-images.githubusercontent.com/1194128/51390303-878cba00-1af4-11e9-905a-c7eb21dc01ea.png)

'Final' ERCs:

- [x] [20](https://github.com/ethereum/EIPs/issues/20)
- [x] ~[165](https://github.com/ethereum/EIPs/issues/165)~ #215
- [x] [721](https://github.com/ethereum/EIPs/issues/721) #225 

'Draft' ERCs:

- [x] [223](https://github.com/ethereum/EIPs/issues/223)
- [x] [621](https://github.com/ethereum/EIPs/issues/621)
- [x] [777](https://github.com/ethereum/EIPs/issues/777)
- [x] [827](https://github.com/ethereum/EIPs/issues/827)
- [x] [884](https://github.com/ethereum/EIPs/issues/884)

**Comment by CoreytMayweather** [comment]
![](https://101blockchains.com/wp-content/uploads/2018/07/ERC_Standards_w.png)

**Comment by CoreytMayweather** [comment]
![image](https://user-images.githubusercontent.com/42082720/51445068-4ea43f00-1cc6-11e9-8616-15bf5c07dc63.png)

**Comment by jmank88** [comment]
Many of these are still in 'draft' status, but we will keep an eye on them. Regardless, I would think that we could recognize at least the ERC/GO-20 subset of the interface, and work with that.

**Comment by CoreytMayweather** [comment]
Some of their interfaces like the 621 and 777, could be usedful. Blacklisting their funds, also an option to destroy them(also decreasing supply option ;ERC621). Then replacing the amount by destroying those funds and creating new ones(also increasing Supply option ;ERC621). There has to be some major governance on this though, as bad parties could increase and decrease supply whenever they feel like it. Blacklist and destroy whomever account they want, and simply generate new tokens for their own will. Blacklisting an address could work in the case of someone hacking an exchange and trying to send those Go Tokens to an GO based DEX. As soon as the blacklisted address touches the DEX, it'll automatically be notified of a blacklisted address and the blacklisted address blocked from use on the DEX.

**Comment by bergauz** [comment]
@jmank88 @treeder should we close this issue or will be updated periodically?

**Comment by treeder** [comment]
We can open separate ones for any others we want to support. Nice work!
