### ISSUE TITLE
ERC-165

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#215]
[ERC-165](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-165.md) "Creates a standard method to publish and detect what interfaces a smart contract implements."

Explorer should check if a contract implements 165, and if so it should utilize `supportsInterface(interfaceID)` to check for any common interfaces that can be used (e.g. ERC-20).

Related to (and probably blocking) #212

**Comment by jmank88** [comment]
Each call costs up to 30,000 gas, so this may not be a scalable option.

**Comment by bergauz** [comment]
extracted interfaces from bytecode

**Comment by jmank88** [comment]
> b9d4b9a

@bergauz This is an alternative to ERC-165, correct? We can't actually use it for free?

**Comment by bergauz** [comment]
@jmank88 as you've seen if needed we can store interfaces that bytecode supports to db and show them in contract page, smth like https://github.com/gochain-io/explorer/issues/176

**Comment by bergauz** [comment]
@jmank88 @treeder closing?
