### ISSUE TITLE
Wallet: Ability to use contract right after deploying (same as old wallet)

### ISSUE THREAD

**Issue by treeder** [gochain-io/explorer#220]
Comment on discord:

> Elegant UI update on the wallet! Noticed that though when deploying a new contract, you now have to reload the page and input the private key again to access the contract where as in the past UI you could just switch to the “interact with contract tab “.

Let's make it so you don't have to reload to continue using the wallet, you just put in your key once then do many things.

**Comment by bergauz** [comment]
@treeder can I close it?
