### ISSUE TITLE
Homepage Block Cards

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#223]
Block cards on the homepage (mobile view) display scroll bars even when the content fits:
![screenshot from 2019-01-28 08-51-01](https://user-images.githubusercontent.com/1194128/51844091-0a262e00-22da-11e9-82ef-f2ef57d0200e.png)
They should be hidden unless necessary.

Additionally, we should pick icons for txs and extra data. Which icon set are we using?

**Comment by bergauz** [comment]
@jmank88 what browser do you use? with chrome on mac looking fine

**Comment by jmank88** [comment]
Chrome on Linux has this problem. The div (`class="tr-card"`) appears to have `overflow-x: scroll` - shouldn't it be `auto`?
