### ISSUE TITLE
Add automatic GO-721 / ERC-721 support

### ISSUE THREAD

**Issue by treeder** [gochain-io/explorer#225]
Detect GO-721 contracts and display all the appropriate information. 

Should also be able to look at a particular item and view all the metadata about it along with the image of it. See https://docs.opensea.io/docs/2-adding-metadata for more information.

**Comment by treeder** [comment]
@bergauz where are we at with this?

**Comment by treeder** [comment]
For the particular item, after searching for it, have the URL be something like:

https://explorer.gochain.io/token/CONTRACT_ADDRESS/asset/TOKEN_ID

TOKEN_ID being the particular assets ID. The page to view the item would called `tokenURI(tokenID)` to get the metadata, then display it along with the image in the metadata.

**Comment by treeder** [comment]
BTW, on testnet and mainnet, this is a live contract address with some assets:

0x29af464A1099Ddf11C5770d8E05CBa18cAeF47d4

**Comment by bergauz** [comment]
> For the particular item, after searching for it, have the URL be something like:
> 
> https://explorer.gochain.io/token/CONTRACT_ADDRESS/asset/TOKEN_ID
> 
> TOKEN_ID being the particular assets ID. The page to view the item would called `tokenURI(tokenID)` to get the metadata, then display it along with the image in the metadata.

@treeder does address need to be exactly like you wrote since we use addr/address instead of token?

**Comment by treeder** [comment]
That's how etherscan does it, good to be consistent with the norm: https://etherscan.io/token/0x06012c8cf97bead5deae237070f9587f8e7a266d#inventory

Could we alias token?  (but only work if it's a token contract?)

**Comment by bergauz** [comment]
@treeder yes

**Comment by bergauz** [comment]
@treeder is there's metadata json structure? cause what i've checked here https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md and https://docs.opensea.io/docs/2-adding-metadata are different

**Comment by treeder** [comment]
One's in JSON schema format so it looks different, but the main ones are the following and the JSON will look like this, so just display these 3 values. 

```json
{
  "name": "Dave Starbelly",
  "description": "Friendly OpenSea Creature that enjoys long swims in the ocean.", 
  "image": "https://storage.googleapis.com/opensea-prod.appspot.com/puffs/3.png"
}
```

**Comment by bergauz** [comment]
@treeder @jmank88  we can close issue, right?

**Comment by jmank88** [comment]
IMHO the `token` page is not accessible enough. It should at least be linked from the normal contract page, or better yet merged together with it.

**Comment by treeder** [comment]
Agree, need an obvious way to access it from main contract page (or merge like @jmank88 said).

**Comment by treeder** [comment]
@bergauz let's merge /token/ and /addr/ 

They both have token like information, but one has different stuff than the other. Let's just make them the same page, make the /token an alias for /addr and take the extra things like the "Token type" chips and things from /token and add them to /addr.

**Comment by bergauz** [comment]
since support added, closing
