### ISSUE TITLE
Use International Date/Time Standard

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#234]
I keep getting thrown off by ambiguous dates, like:
![screenshot from 2019-03-02 09-39-27](https://user-images.githubusercontent.com/1194128/53684133-23523e00-3ccf-11e9-9a87-7a9dcc5e3ce0.png)

We should use an international date/time standard like, [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) or [RFC 3339](https://tools.ietf.org/html/rfc3339).

**Comment by bergauz** [comment]
<img width="291" alt="screenshot 2019-03-05 at 06 42 42" src="https://user-images.githubusercontent.com/42649300/53772783-efb32600-3f11-11e9-83aa-05920cf2f93b.png">

**Comment by r-gochain** [comment]
@jmank88 does it work for you?

**Comment by jmank88** [comment]
The PR (#235) still has some open questions. I think the simple change of swapping `dd/MM/yyyy` for `yyyy/MM/dd` is a better way to start.

**Comment by bergauz** [comment]
@jmank88 changed to dd/MM/yyyy HH:mm:ss local time
