### ISSUE TITLE
Add number of confirmations to tx page

### ISSUE THREAD

**Issue by treeder** [gochain-io/explorer#236]
Which is just latest block number - block of transaction.

eg on etherscan:

![screenshot 2019-03-05 at 10 13 54 pm](https://user-images.githubusercontent.com/75826/53853592-174ad280-3f94-11e9-9925-c1de6e325239.png)

**Comment by bergauz** [comment]
<img width="673" alt="Screenshot 2019-03-27 at 16 22 10" src="https://user-images.githubusercontent.com/42649300/55068639-848de700-50ac-11e9-89cb-33a628062ff3.png">

**Comment by bergauz** [comment]
it updates every 5 sec

**Comment by treeder** [comment]
I'm not seeing this @bergauz ?

**Comment by bergauz** [comment]
@treeder fixed
