### ISSUE TITLE
Wallet: Support custom RPC

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#241]
It seems like wallet is hard coded to only support the public main/test rpc endpoints. Instead, it should connect to whatever rpc url the web server is using to fetch data. i.e. if you are running a local dev network, or a private network, you should be able to use explorer's wallet.

**Comment by bergauz** [comment]
// "Web3.providers.givenProvider" will be set if in an Ethereum supported browser.
const web3 = new Web3(Web3.givenProvider || 'https://rpc.gochain.io');
is it gonna work? or need input field to enter provider manually

**Comment by jmank88** [comment]
I don't totally understand how givenProvider is supposed to work, but that doesn't seem right. It needs to match the backend, however that is best achieved. Maybe just a service call for the url.

**Comment by bergauz** [comment]
@jmank88 we can store provider url in angular environment file

**Comment by jmank88** [comment]
Are those dynamic? It needs to match RPC_URL or the flag passed to the backend, which could be anything

**Comment by bergauz** [comment]
we can use environment variable on top of it

**Comment by jmank88** [comment]
I'm not sure I understand. The environment variable `RPC_URL` and the flag `rpc-url, u` are the source of truth here. I don't know what the best way to get those values to the front end is, but that is where the information must come from.

**Comment by bergauz** [comment]
EV RPC_URL - we use while building front, flag rpc-url -u we use at back and there is only one way to get it - make request

**Comment by jmank88** [comment]
Then we need to make a request. This cannot be compile time, it must be run time. 
A simple broken use case is the local dev compose file: https://github.com/gochain-io/docs/blob/master/private-networks/local/docker-compose.yml, but in general users need to be able to point pre-built images at any endpoint they want, without compiling anything.
