### ISSUE TITLE
Validating contracts not working. 

### ISSUE THREAD

**Issue by treeder** [gochain-io/explorer#243]
From user: I have already verified many times, but it always show message "HE COMPILED RESULT DOES NOT MATCH THE INPUT CREATION BYTECODE LOCATED AT 0X473A70391D961D1D81044F7E2B69EECD59DC355C" Please help me verify smart contract on GoChain Network with step by step guide.

**Comment by jmank88** [comment]
Could it be the solidity version producing different bytecode? Can we use the web3 approach of fetching the requested version and running in docker?

**Comment by jmank88** [comment]
Related #211

**Comment by r-gochain** [comment]
Solidity is definitely producing different code for different versions

**Comment by treeder** [comment]
Or allow the user to select the version to compare it against.

**Comment by r-gochain** [comment]
deployed the update where you could select the compiler version

**Comment by r-gochain** [comment]
I was able to compile code with web3, upload to gochain and verified using explorer (selected proper version of solc compiler in the dropdown)

**Comment by bergauz** [comment]
since no issues with contract validation - closing
