### ISSUE TITLE
Mobile shows old logo

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#248]
![Screenshot_20190329-151234](https://user-images.githubusercontent.com/1194128/55259971-26404000-5235-11e9-8981-79b5dcd323a2.png)

**Comment by bergauz** [comment]
<img width="463" alt="Screenshot 2019-04-01 at 17 31 52" src="https://user-images.githubusercontent.com/42649300/55324495-1aa68080-54a4-11e9-9d6d-db6f0ace4ac3.png">
