### ISSUE TITLE
add known interface abi with ui to contract's page

### ISSUE THREAD

**Issue by bergauz** [gochain-io/explorer#255]

**Comment by treeder** [comment]
This would be very useful, let's just do ERC20 and ERC721 to start.

**Comment by jmank88** [comment]
Probably overlaps with #263

**Comment by jmank88** [comment]
I was thinking about how this might behave, particularly in the cases when we don't detect an interface, but the user knows it will work (e.g. I'm guessing upgradeable contracts aren't detected correctly). What about allowing users to add interfaces to their view, in addition to whatever we detect? This way they aren't blocked if our detection fails, and if the interface they choose works then we can save that information in the database.

Maybe they click a plus/add button then choose from a pop-up picker:
![Screenshot from 2019-04-20 17-59-30](https://user-images.githubusercontent.com/1194128/56463253-1af4b600-6396-11e9-814e-3cf720b21a3c.png)
```
Token type: [+]
[ERC20] [ERC165]
```
We could also allow them to remove/hide interfaces, e.g. if they want to focus on a single one.
```
[ERC20|X] [ERC165|X]
```

**Comment by treeder** [comment]
I think this is more for the wallet part @jmank88 , here: https://explorer.gochain.io/wallet/send 

Enter contract address, choose a type from a drop down or paste in your own ABI, then you can interact with it. Although it would be nice to integrate the wallet part into the token pages too.

**Comment by jmank88** [comment]
OK then the visual component only applies to #263, but the rest still applies here. We need to let them use interfaces we can't detect, and we can keep track of which method calls are successful to learn the interfaces we don't detect.

**Comment by bergauz** [comment]
<img width="1280" alt="Screenshot 2019-04-23 at 11 09 02" src="https://user-images.githubusercontent.com/42649300/56556164-0e03dc80-65b9-11e9-84bf-bf39535852e6.png">
<img width="1280" alt="Screenshot 2019-04-23 at 10 49 50" src="https://user-images.githubusercontent.com/42649300/56556165-0e9c7300-65b9-11e9-853a-f73d68be7aac.png">
<img width="1280" alt="Screenshot 2019-04-23 at 10 49 43" src="https://user-images.githubusercontent.com/42649300/56556167-0e9c7300-65b9-11e9-90c0-2b7e267e43af.png">
<img width="1280" alt="Screenshot 2019-04-23 at 10 48 59" src="https://user-images.githubusercontent.com/42649300/56556169-0e9c7300-65b9-11e9-8082-335b6f45a9a9.png">
<img width="1048" alt="Screenshot 2019-04-23 at 10 40 58" src="https://user-images.githubusercontent.com/42649300/56556170-0f350980-65b9-11e9-91a4-4f8f20378a83.png">

**Comment by treeder** [comment]
Looks awesome!  One issue I had though is that it defaults to 21000 gas which I don't think will work for any contract. I increased the gas and it worked though. Can we have it default to nothing then use the estimated gas figure when sending? Or get estimated gas and fill in the field appropriately?

**Comment by treeder** [comment]
Another thing, could we have it get the "decimals" then when you do a transfer, it will calculate that properly to make it more human friendly? I always make the mistake of sending 1 which turns into 0.000000000000000001

**Comment by bergauz** [comment]
@treeder got it

**Comment by treeder** [comment]
One more thing: on the "Transaction complete!" page it has a "Cancel" button. That should say "Done" or something instead of Cancel.

**Comment by treeder** [comment]
Also, if it already knows it's an ERC20 (which it does), let's just fill in the ABI when it loads rather than having to click the little blue button.
