### ISSUE TITLE
QR Code

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#256]
We should consider displaying account QR codes on the address and wallet pages, and serving the raw image over an api url, e.g. `https://explorer.gochain.io/api/qr/<addr>` (maybe an extension as well, if it makes sense to provide more than one of `.png`, `.svg`, etc.)

**Comment by bergauz** [comment]
@jmank88 so qr url is /api/address/{{addr.address}}/qr

**Comment by jmank88** [comment]
Wait, we already have this? Where is it displayed?

**Comment by jmank88** [comment]
These commit references are confusing me

**Comment by jmank88** [comment]
#257

**Comment by treeder** [comment]
That URL doesn't work for me @bergauz , eg: https://explorer.gochain.io/api/address/0x37C93A80b5702A820CbC3050f0e9eC48a1D5e738/qr

Can you have it automatically show on the /addr/ADDRESS page?

**Comment by jmank88** [comment]
I don't think anything has been merged/deployed yet

**Comment by jmank88** [comment]
We should consider a more general service that can accept any text, and produce a stylized (optional?) QR code. The addresses specific path can stay but another like `/api/qr?text=asdf&logo=true` would be good. This way text can be anything (address, tx hash, url to turbo wallet claim, etc.).
