### ISSUE TITLE
Tx Receipt Status

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#259]
The testnet tx `0xc1368648ee04a97c06fa5b293c8743420c79b2628fd6424616bb9f78fb6565fd` failed, but you wouldn't know if from the interface:
![Screenshot from 2019-04-08 18-03-25](https://user-images.githubusercontent.com/1194128/55762494-bc8c1700-5a28-11e9-89f3-ca1d5506260a.png)
https://testnet-explorer.gochain.io/tx/0xc1368648ee04a97c06fa5b293c8743420c79b2628fd6424616bb9f78fb6565fd

We already check gas used from the receipt, we should check the status as well. Probably Logs too, but that could be complicated and can be done separately later.

**Comment by bergauz** [comment]
<img width="901" alt="Screenshot 2019-04-09 at 17 37 10" src="https://user-images.githubusercontent.com/42649300/55797689-e3ad1c00-5aee-11e9-8fd2-06358e28b93c.png">
