### ISSUE TITLE
Block Hash Search

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#262]
We should support searching by block hash:
![Screenshot from 2019-04-10 13-47-18](https://user-images.githubusercontent.com/1194128/55905239-36daa980-5b97-11e9-920c-4bf7e4546a36.png)
The current behavior is to assume it's a tx hash, and then show 'not found'. Instead we should determine what it is and then jump to the correct page.

**Comment by bergauz** [comment]
@jmank88 as I know there's no difference between tx hash and  block hash?

**Comment by bergauz** [comment]
we could make request to server to check if tx hash exists, if not check block hash, if not show no found

**Comment by jmank88** [comment]
That sounds good. Maybe try to write it in a general way so that we can add e.g. receipt hashes later too.
