### ISSUE TITLE
Contract Page Malformed

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#278]
Just after deploying a contract, the page is in a weird state:
![Screenshot from 2019-04-25 13-33-53](https://user-images.githubusercontent.com/1194128/56759538-ccad3180-675e-11e9-9be4-064420efdfa1.png)
https://testnet-explorer.gochain.io/addr/0x445511b9DD47aD2b8103d45fa50cA0555dd8f452

**Comment by jmank88** [comment]
Working now, so maybe only a problem before the data has been grabbed.

**Comment by bergauz** [comment]
@jmank88 yes, we can make as we've made with tx page, if no data in server use web3

**Comment by jmank88** [comment]
We can't trigger the grabber, since it's a separate process, but could the server do the same work itself and update the database safely? Or would it clash with the grabber's process? @r-gochain

**Comment by r-gochain** [comment]
seems like fixed with the most recent code rolled out
