### ISSUE TITLE
Make wallet mobile friendly

### ISSUE THREAD

**Issue by treeder** [gochain-io/explorer#279]
Could easily be put into a flex grid or something I would think. 

Currently looks like this:

![photo5050814573422159897](https://user-images.githubusercontent.com/75826/56836807-22e8a600-682d-11e9-85ac-5ff1bb15033c.jpg)

**Comment by treeder** [comment]
I'm not sure if we're using this in explorer, but we probably should be: https://github.com/angular/flex-layout

**Comment by bergauz** [comment]
@treeder yes, work in progress

**Comment by brockmcblockchain** [comment]
I can help if need be.  Just holla.

**Comment by bergauz** [comment]
closed by #337
