### ISSUE TITLE
Include Token Balances on Address Page

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#285]
We already index token transfer txs for each contract. For each account involved in those txs, we should also fetch and store the token balances (like the normal GO balance information), and display them on the address page.

Something like:
```
Tokens:
12345 TURBO
56788 GOST
```
With the symbol names linking to the contracts.

This is pretty straightforward for ERC20s. If ERC721s are too messy (UI could be complicated since they could hold a ton and we might need to page through lists or something), then they can be done later in a separate change.

We could also consider adding a `Token Transfers` tab just like `Internal Transactions` from the contract page, which includes only token transfer txs to/from this account.

**Comment by bergauz** [comment]
@jmank88 what's strategy to update token balance?

**Comment by jmank88** [comment]
I don't know the grabber internals well enough to be sure, but it seems like it could be part of the normal GO balance update process, or an analogous process that works in the same general way. Maybe @r-gochain has some ideas.

**Comment by r-gochain** [comment]
Yeah I'm going to work on this today

**Comment by r-gochain** [comment]
![image](https://user-images.githubusercontent.com/40002763/57102768-f0f3aa00-6d2c-11e9-98ac-2241bf504863.png)

**Comment by r-gochain** [comment]
@bergauz could you add frontend part for this ticket? 
I've added a new API endpoint(the same as /holders) - api/address/TOKEN_OWNER_ADDRESS/owned_tokens?limit=25&skip=0

**Comment by jmank88** [comment]
Sweet that was easy! Fetching the internal txs to/from an account should be pretty easy too, yeah? Just another index or two on existing data?

**Comment by r-gochain** [comment]
![image](https://user-images.githubusercontent.com/40002763/57164224-1dc2c280-6dfc-11e9-89eb-b77559fffe4a.png)

**Comment by r-gochain** [comment]
@bergauz added token_transactions parameter (/api/address/ADDRESS_HASH/internal_transactions?token_transactions=true&limit=25&skip=0)

**Comment by r-gochain** [comment]
@bergauz have you added Token transfers too?(I remember I saw it, just to confirm)

**Comment by bergauz** [comment]
@r-gochain yes

**Comment by bergauz** [comment]
closed by #290, #300
