### ISSUE TITLE
Verified Source Timestamp

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#287]
This contract source was verified 2020 years ago :confused: 
![Screenshot from 2019-05-01 14-27-23](https://user-images.githubusercontent.com/1194128/57037646-62dcce00-6c1d-11e9-8162-364420a2fb40.png)
https://testnet-explorer.gochain.io/addr/0xFD36929292a1a5A90b6d1F20f0003400868721D3?addr_tab=contract_source

**Comment by bergauz** [comment]
@jmank88 @r-gochain 
somehow https://github.com/gochain-io/explorer/blob/42d0e6992052d93193032bedb427a182ca541401/server/backend/backend.go#L205 hasn't worked

**Comment by jmank88** [comment]
It is showing up to the front end like this:
![Screenshot from 2019-05-02 09-34-15](https://user-images.githubusercontent.com/1194128/57083014-7c355700-6cbd-11e9-9f79-6e1a7df47d9c.png)

**Comment by bergauz** [comment]
@jmank88 @r-gochain  smth strange happening 

`abi: null
address: "0x1997eF6BeE5d61979E63d0c6b40F6d185Ab1156D"
created_at: "0001-01-01T00:00:00Z"
updated_at: "0001-01-01T00:00:00Z"`

but there's data in mongodb

`abi:Array
created_at:2019-05-11 00:53:43.617
updated_at:2019-05-11 15:53:13.193`

**Comment by bergauz** [comment]
related #227

**Comment by jmank88** [comment]
Could this be another upsert with fields missing `omitempty`?

**Comment by r-gochain** [comment]
Yeah we figured out the issue with date, but for Abi it seems like need to create serializer/deserializer

**Comment by r-gochain** [comment]
![image](https://user-images.githubusercontent.com/40002763/58830892-09b8ed80-8654-11e9-8265-4402922ba2c2.png)
