### ISSUE TITLE
ERC20 balanceOf output should format with decimals

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#291]
ERC20 balances are displayed in their internal form, without considering the decimals specified by the contract.
![image (2)](https://user-images.githubusercontent.com/1194128/57252579-1117b780-7012-11e9-81fc-7719db063ce6.png)
This could be confusing to users, although in some cases they may actually want to know the raw value, so we may not want to take it away entirely. We should at least provide the adjusted decimal value in addition to the raw value, if not in place of it entirely. For example: `12345 (0.12345 TURBO)`

**Comment by treeder** [comment]
Could we also make it so the "Transfer" function can use the human friendly decimal format too?  With perhaps a switch to the raw format. I had this in #255 

>Another thing, could we have it get the "decimals" then when you do a transfer, it will calculate that properly to make it more human friendly? I always make the mistake of sending 1 which turns into 0.000000000000000001

**Comment by jmank88** [comment]
A general solution here would be the ability to somehow annotate the inputs and outputs of various ABI functions with 'transformers' that convert between the internal values and human friendly values. That could be complicated to do completely and generally though, so some special case code in the front-end for ERC20s only seems reasonable to start.

**Comment by jmank88** [comment]
For input, maybe let them enter the human readable decimal value, and then live update the corresponding raw value next to it:
```
TURBO: [1] (10000000000000000)
TURBO: [.05] (500000000000000)
TURBO: [.000000000000000001] (1)
```
