### ISSUE TITLE
Estimated gas

### ISSUE THREAD

**Issue by bergauz** [gochain-io/explorer#303]
Looks awesome!  One issue I had though is that it defaults to 21000 gas which I don't think will work for any contract. I increased the gas and it worked though. Can we have it default to nothing then use the estimated gas figure when sending? Or get estimated gas and fill in the field appropriately?

_Originally posted by @treeder in https://github.com/gochain-io/explorer/issues/255#issuecomment-488295561_

**Comment by treeder** [comment]
Probably a short term fix for this is to  just set it higher on contracts, because **zero** contracts will work at the 21000 that is set now. Set it to 50,000 or something (it only takes what i uses anyways).

Then after we get that out, we can use estimateGas in web3.js.
