### ISSUE TITLE
Change page title for token contract pages

### ISSUE THREAD

**Issue by treeder** [gochain-io/explorer#306]
When on a token contract page with a "symbol" and "name" value, change the page title so it shows up in the browser tabs to:

"{SYMBOL} - {NAME} - GoChain Explorer"

**Comment by jmank88** [comment]
![Screenshot from 2019-05-14 11-19-50](https://user-images.githubusercontent.com/1194128/57714474-34f28300-763a-11e9-9a62-d4fd7c102001.png)
