### ISSUE TITLE
Owned Tokens tab lost the token name

### ISSUE THREAD

**Issue by treeder** [gochain-io/explorer#311]
![Screenshot 2019-05-14 at 9 59 34 PM](https://user-images.githubusercontent.com/75826/57743577-9eeb4680-7693-11e9-9f6f-ce19835ad741.png)

**Comment by r-gochain** [comment]
hmm I don't see any issues

![image](https://user-images.githubusercontent.com/40002763/57830256-35b22300-77ba-11e9-83d3-c94180949b73.png)

**Comment by jmank88** [comment]
I also had no token names at one point, but now they work.
