### ISSUE TITLE
Some things aren't loading when switching pages, which do load when you enter the URL directly

### ISSUE THREAD

**Issue by treeder** [gochain-io/explorer#318]
For instance, going from the wallet, after entering key and clicking "View Address", the token transactions don't show up. Here is viewing the page directly:

![photo5114369377754523684](https://user-images.githubusercontent.com/75826/57930185-4e3a4000-7883-11e9-9b89-03e09bf411c5.jpg)

Here it is when clicked from "View Address" in the wallet:

![photo5114301920998172684](https://user-images.githubusercontent.com/75826/57930211-5f834c80-7883-11e9-8fb8-d9aeb6c9899c.jpg)

**Comment by bergauz** [comment]
@treeder it was bug with tab url detector, it's already fixed, needs server update

**Comment by r-gochain** [comment]
@bergauz I found a different bug on the same place - when you click on pagination links it doesn't load the proper list of Token Transactions ie

https://testnet-explorer.gochain.io/addr/0x5eCE2AE4109836b90AF4A3deE896e40d6A227e61?addr_tab=token_transactions

try to click 1,2 and then 1 again

**Comment by bergauz** [comment]
fixed by #338 and #313
