### ISSUE TITLE
Signers Page

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#334]
Add a new page for signer information at `/signers` and linked as "Signers" in the main nav. This page should contain a table of signer account information (address, name, url, region) with stats about blocks signed (count, %), and a pie chart like the following (from https://www.blockchain.com/en/pools):

![Screenshot from 2019-07-08 11-29-44](https://user-images.githubusercontent.com/1194128/60998286-37154d00-a31e-11e9-9340-4c73f6143164.png)

Caption: `Block Signers for 9768 blocks from <start ts> to <end ts>`

| Account | Name | Region | Blocks | % |
| ------ | --- | --- | --- | --- |
| [0x1](https://explorer.gochain.io/addr/0x1) | [GoChain 1](https://gochain.io) | North America | 100 | 4% |
| [0x2](https://explorer.gochain.io/addr/0x2) | [GoChain 2](https://gochain.io) | South America | 102 | 4.1% |

The data should be available for a fixed set of ranges, like 1d, 7d, 30d, and groupable by region if possible.

One possible data format:

```go
type SignerDistribution struct {
  Start, End uint64 // unix ts for queried ranged
  TotalBlocks uint64 
  Signed []struct {
    Address common.Address
    Blocks uint64
  }
}
```

The service would then return a fixed set of ranges (e.g. 1d, 7d, 30d), which can each be independently cached and refreshed on their own schedules.

```go
type SignerDistributions struct {
  Day, Week, Month SignerDistribution  // 1d, 7d, 30d
  Signers []struct {
    Address common.Address
    Name string
    URL string
    Region string
  }
}
```

The extra `Signers` information will have to be loaded from a configuration file. This info can be used to enhance the UI in other places, e.g. by adding name/url to pages for accounts, blocks, rich list (related #125), and the homepage. Example `signers.json`:
```json
[
  {
    "address": "0xA",
    "name": "GoChain 1",
    "url": "https://gochain.io",
    "region": "North America"
  },
  ...
]
```

**Comment by bergauz** [comment]
closed by #336
