### ISSUE TITLE
Display small values in different units

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#34]
![screenshot from 2018-05-26 11-17-47](https://user-images.githubusercontent.com/1194128/40578268-895715d4-60d6-11e8-8097-04930001df92.png)
Gas price, at least, is commonly displayed in `gwei`. Maybe we could dynamically display small values in other units as well.

**Comment by rkononov** [comment]
![image](https://user-images.githubusercontent.com/187434/40623232-943b2b64-62c7-11e8-9d8b-67e56d1f0a13.png)
