### ISSUE TITLE
Discussion: Daily DB dumps for import

### ISSUE THREAD

**Issue by gateway** [gochain-io/explorer#41]
I think it might make sense to look at doing daily mongo dumps to a s3 bucket from all the block data that was captured.  This would potentially help anyone wanting to create an explorer or some other app the ability to import this data first instead of doing a full grab from the start.. 

Only thing I'm not 100% sure on is if during the day or days if the # of transactions change.. maybe this could be synced quicker.. 

thoughts?

**Comment by treeder** [comment]
We do plan on having higher volume API to access older blocks, directly from a service like S3. It wouldn't be a mongo dump, but some way to get all the data you need.
