### ISSUE TITLE
Format Tx table 'GO' column

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#46]
Should we format this tx column like in #28 ?
![screenshot from 2018-06-01 12-39-37](https://user-images.githubusercontent.com/1194128/40855285-d3500f2a-6599-11e8-95c9-fe28f4110b3f.png)
Perhaps it should be right-aligned as well.

**Comment by bergauz** [comment]
<img width="514" alt="screen shot 2018-09-29 at 11 13 21" src="https://user-images.githubusercontent.com/42649300/46241314-bad9fa80-c3d8-11e8-9136-16c318144dda.png">
so it's formatted. about right alignment: i think if we are going to do this we need to unify digits qty after comma so it'll be obvious to user, either there's no sense to do it

**Comment by jmank88** [comment]
Is it easy to align on the decimal?
```
 123.456
  12.2345
1234.5
```
Maybe also drop the per-line `GO` and just have it up top like `VALUE (GO)` or something?

**Comment by bergauz** [comment]
<img width="1280" alt="screenshot 2018-10-08 at 13 39 28" src="https://user-images.githubusercontent.com/42649300/46597021-3be37100-cb00-11e8-8c2a-8f13c2537633.png">
 @jmank88  Droped per line GO, but it's difficult to aligning on decimal since it's dynamic list, put fixed fraction

**Comment by jmank88** [comment]
I'm worried a fixed fraction is going to be a problem. Can we do the max 18 decimals, but replace trailing zeros with spaces?

Whatever we do, the rich list should be the same:

![screenshot from 2018-10-08 09-08-03](https://user-images.githubusercontent.com/1194128/46620660-29564100-cada-11e8-9919-8936e3e44c2f.png)

**Comment by bergauz** [comment]
<img width="602" alt="screenshot 2018-10-10 at 02 47 04" src="https://user-images.githubusercontent.com/42649300/46697685-fe353400-cc36-11e8-80b5-eec9f99a696b.png">

**Comment by bergauz** [comment]
<img width="985" alt="screenshot 2018-10-15 at 18 50 53" src="https://user-images.githubusercontent.com/42649300/46952551-fc42f900-d0ac-11e8-99b4-c83e1de4fd44.png">
<img width="687" alt="screenshot 2018-10-15 at 18 51 09" src="https://user-images.githubusercontent.com/42649300/46952552-fc42f900-d0ac-11e8-8573-a4ed49023ce3.png">
