### ISSUE TITLE
Add 'Tx does not exist' placeholder

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#47]
Looking up a transaction which does not exist should hide the usual details completely, and just inform the user that the transaction 'could not be found' or 'does not exist'.
![screenshot from 2018-06-01 13-12-12](https://user-images.githubusercontent.com/1194128/40856417-6e7630bc-659d-11e8-8ffa-bfe76cd78603.png)

**Comment by bergauz** [comment]
<img width="920" alt="screen shot 2018-09-28 at 14 56 20 1" src="https://user-images.githubusercontent.com/42649300/46198598-af31f980-c32e-11e8-9eb3-d4178c2a9bd7.png">

**Comment by bergauz** [comment]
<img width="1066" alt="screenshot 2018-10-15 at 21 42 26" src="https://user-images.githubusercontent.com/42649300/46961735-4040f880-d0c3-11e8-991f-c803863483f4.png">
