### ISSUE TITLE
Txs missing from index

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#64]
https://explorer.gochain.io/addr/0xacb348b684dd6539817a65b3641735f47435cec0
The balance and transaction count (2) for this address is correct, but the index is missing one of the sent txs, making the balance look incorrect.
![screenshot from 2018-06-11 02-50-02](https://user-images.githubusercontent.com/1194128/41218861-2db5a88c-6d22-11e8-8844-2bc2ec9d6d07.png)

**Comment by jmank88** [comment]
Looks fixed by #68

**Comment by treeder** [comment]
People still having this issue.

**Comment by nonergodic** [comment]
issue continues to exist:
https://explorer.gochain.io/addr/0x16e25ab5189eb94640c31c9a2661cc9d8ff35e8a
https://explorer.gochain.io/addr/0xa0a06ee0418629a73fbfebc355e48d345f5f60ef
There should be at least one transaction from the first account to the second for 1875 with nonce3.
The page also fails to show at least one additional transaction for the second account, seeing how it only shows the initial transaction for 52574.97921 GO, but there is 1,875.018711 GO on the account (i.e. the 1875 from the missing transaction + apparently some leftovers).

**Comment by r-kononov** [comment]
@nonergodic fixed
