### ISSUE TITLE
Combine From/To Columns

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#69]
This is a tx list table for an account:
![screenshot from 2018-06-19 13-14-32](https://user-images.githubusercontent.com/1194128/41616116-bda4da20-73c2-11e8-8b1c-e006f921649d.png)

The account's address is listed on every row as either the sender or receiver. We could save some space (and use it to display the full address?) by only displaying the 'other' address, and using inline labels, colors, or symbols to designate send vs. receive.

| Other | GO |
| --------|------- |
| From: 0xa | +100 |
| To: 0xb  | -10.5 |

**Comment by bergauz** [comment]
<img width="1280" alt="screen shot 2018-09-28 at 14 54 31" src="https://user-images.githubusercontent.com/42649300/46198498-71cd6c00-c32e-11e8-90be-be2c14a06826.png">
