### ISSUE TITLE
Shows "No Results" when there are results.

### ISSUE THREAD

**Issue by treeder** [gochain-io/explorer#71]
Shows "No Results" when there are results. It should only do this when no rows of data are displayed.

![41689477-9ada4ece-74a5-11e8-9b85-8901ac21562f](https://user-images.githubusercontent.com/75826/41695481-071543aa-74c4-11e8-8c6e-dd4fffa446b7.jpg)

cc @jjstafford

**Comment by chovy** [comment]
Ok, all I did was replace the frownie face with "no results" so I guess there's a bug there. I'll see if I can figure out why that is happening. Is there an address that has no results and one with results you can give me?

**Comment by treeder** [comment]
Are you sure the smiley face had anything to do with no results?

**Comment by chovy** [comment]
This is where the frownie face was. I just replaced it with the words "No results". But I don't understand how it gets displayed because I don't see it referenced anywhere.

https://github.com/gochain-io/explorer/blob/master/public/js/controllers/AddressController.js#L61

**Comment by r-kononov** [comment]
fixed
