### ISSUE TITLE
Add a "richlist" page

### ISSUE THREAD

**Issue by treeder** [gochain-io/explorer#73]
List of token holders sorted by amount.

**Comment by jmank88** [comment]
https://github.com/gochain-io/gochain/pull/228

**Comment by r-kononov** [comment]
https://www.coinexplorer.net/EMB/richlist

**Comment by jmank88** [comment]
Do we need any more info than these columns?

|Rank|Address|Balance|Supply Owned|
|-------|-----------|-----------|-------------------|
| #1 | 0xabcd | 100 | 5.04%|

If we are using *circulating* supply, then we should exclude accounts which are locked (can share the configuration needed for https://github.com/gochain-io/explorer/pull/74)

**Comment by chovy** [comment]
I added a stub for the rIch list page.
