### ISSUE TITLE
__platform_browser_private__ is not present in @angular/platform-browser

### ISSUE THREAD

**Issue by DnyaneshwarShivbhakta** [gochain-io/explorer#90]
I am migrating angular 2 application to angular 6.In angular 2  I am able to use following lines of code but after migrating to angular 6 its giving error.

```
import { __platform_browser_private__ } from '@angular/platform-browser';
import { __core_private__ } from '@angular/core';
```

**Comment by treeder** [comment]
This is the wrong place to ask your angular questions. Try https://stackoverflow.com/
